# fly.toml app configuration file generated for automacaovagasestagio
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "automacaovagasestagio"
primary_region = "gru"

[build]
dockerfile = "Dockerfile"

[mounts]
source="vagas_historico"
destination="/var/data"